### PR TITLE
IDE 2837: Rename XSemantics to org.eclipse

### PR DESCRIPTION
**Pull request by qtran-n4**
This PR renames Xsemantics to org.eclipse

### CODE REVIEW

**Comment by qtran-n4** [comment]
@mmews-n4 Please review. Thanks!

**Comment by LorenzoBettini** [comment]
Why have you closed the Pr?

**Comment by qtran-n4** [comment]
@LorenzoBettini the PR is intended for our fork: https://github.com/mmews-n4/xsemantics/pull/7

**Comment by LorenzoBettini** [comment]
I don't understand, shouldn't the renaming being applied to this repo?

**Comment by mmews-n4** [comment]
You're right, but this is just part of our process: Quang made some changes, that are now under review here: https://github.com/mmews-n4/xsemantics/pull/7 . After this review succeeded, we create a second pull request for your repo.

Actually, this second PR for your repo would not be necessary: We could create the zip for the initial Eclipse contribution from our fork. The advantage then would be, that your repo remains with the current name scheme (and not be changed to org.eclipse...). However, we still would like to create a second PR for the renaming, because then we can test that the renaming did not create some new errors. Whether you would like to merge the renaming is up to you.

**Pull request closed without merging**
