### PR TITLE
Mmews n4 task 90 add copyright headers

### LINKED ISSUE #90: Add copyright headers to all source files
A copyright header should be added to all files that fit the patters below. The header references Lorenzo Bettini as the contributor of the initial contribution and the API.

**Files addressed:**
* *.java, *.xtend, *.xsemantics, *.oldxsem
* README.txt, README.md

**Copyright header (for java and similar files)**
```java
/*******************************************************************************
 * Copyright (c) 2013-2017 Lorenzo Bettini.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Lorenzo Bettini - Initial contribution and API 
 *******************************************************************************/
```

**Copyright header (for README.txt files)**
```
*******************************************************************************
Copyright (c) 2013-2017 Lorenzo Bettini.
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v10.html

Contributors:
  Lorenzo Bettini - Initial contribution and API 
*******************************************************************************
```

**Copyright header (for README.md file)**
```adoc
////
Copyright (c) 2013-2017 Lorenzo Bettini.
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v10.html

Contributors:
  Lorenzo Bettini - Initial contribution and API 
////
```

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Closes #90

### CODE REVIEW

**Comment by mmews-n4** [comment]
Check if this would help: Add it to the xsemantics test files like `ecore_ruleinvocation_test.xsemantics`. A copyright header would then be added, so that the test expectancy also can contain copyright headers at their top.

# Example (Beginning of ecore_ruleinvocation_test.xsemantics):
```
system it.xsemantics.test.ruleinvocation.ecore.TypeSystem

copyright "Copyright (c) 2013-2017 Lorenzo Bettini.
All rights reserved. This program and the accompanying materials
are made available under the terms of the Eclipse Public License v1.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v10.html

Contributors:
  Lorenzo Bettini - Initial contribution and API
"

import org.eclipse.emf.ecore.EClass
import org.eclipse.emf.ecore.EObject
import org.eclipse.emf.ecore.EStructuralFeature
import org.eclipse.emf.ecore.EcoreFactory

judgments {
	type |- EClass c1 : EObject o1
//...
```

**Comment by LorenzoBettini** [comment]
@mmews-n4 I'm not sure I understand your suggestion, but I have already updated test expectations, and I'm about to release 1.12.1

**Comment by mmews-n4** [comment]
The grammar `Xsemantics.xtext` was extended by @JensN4 so that it has the optional variable `copyright` now. We could use it so that the generated files `TypeSystem` and `TypeSystemValidator` contain the given copyright.

**Comment by LorenzoBettini** [comment]
Yes, and I've already updated the test expectations with that respect https://github.com/LorenzoBettini/xsemantics/pull/92/commits/4b30cac14b8f16d1529d99f3346a87c4a048d652

**Pull request merged**
